version: '3'
services:
  backend:
    build: /Users/I526724/Personal_Projects/InkedBackend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
  frontend:
    build: /Users/I526724/Personal_Projects/Inked/inked
    ports:
      - "8080:80"
    depends_on:
      - backend
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /Users/I526724/Personal_Projects/InkedBackend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
